config/routes.rb
Rails.application.routes.draw do
    get "products/get_title"

    root 'static_pages#home'
    resources :products
    resources :products do
       get "get_title"
    end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
require 'nokogiri'
require 'open-uri'
#Handles requests for product
class ProductsController < ApplicationController
  respond_to :html,:js

  def create
    prod = ScraperProduct.new(Product.new(w_id:params[:w_id], title:params[:title]), ReviewScraperFactory::WALMART_SCRAPER)
    prod.save
    redirect_to prod
  end

  def index
    @products = Product.all
  end

  #display title of product
  def get_title
    @scraper = ProductScraperFactory.get_scraper(ReviewScraperFactory::WALMART_SCRAPER, params[:url])
  end

  def show
    @product = Product.find params[:id]
  end
end

app/controllers/static_pages_controller.rb
#display home page
class StaticPagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmazonScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/get_title.js.erb
document.getElementById("product_name").innerHTML = "<%=@scraper.product_title%>"
document.getElementById("w_id").value = "<%=@scraper.product_id%>"
document.getElementById("title").value = "<%= @scraper.product_title.html_safe%>"
document.getElementById("product_box").style.visibility = "visible"

app/views/products/index.html.erb
<h1>List of products</h1>
<div>
  <ol>
    <%= render partial: "products/items/product", collection: @products, as: :product%>
  </ol>
</div>

app/views/products/items/_product.html.erb
<li class="product_item"><b><%=product.title%></b> <span class="link_to_product"><small ><%=link_to "Show more",product%></small></span></li>

app/views/products/show.html.erb
<h1><%=@product.title%></h1>
<h3>Product reviews</h3>
<ul>
  <%= render partial: "reviews/items/review", collection: @product.reviews.order(creation_date: :desc), as: :review %>
</ul>

app/views/reviews/items/_review.html.erb
<li class="review_item">
  <div><b> <%=review.title%></b> <small class="review_date"><i><%=review.creation_date%></i></small></div>
  <div><%=review.text%>
</li>

app/views/static_pages/home.html.erb
<h1>Import Walmart product and reviews</h1>
<div>
  <div>
    <%= form_tag({controller: "/products", action:"get_title"}, id:"get_product_title", method:"get", remote:true) do %>
    <%= label_tag :url, "Copy Walmart product url here", class:"url_label"%>
    <%= url_field_tag :url, nil, id:"product_name_field", autocomplete: "off",required:true%>
    <%= submit_tag "Get product name"%>
    <%end%>
  </div>
  <div id="product_box">
    <%= form_tag({controller: "/products", action:"create"}, id:"create_product") do %>
      Product name is <b id="product_name"></b>
      <%= hidden_field_tag :w_id, id:"product_id"%>
      <%= hidden_field_tag :title, id:"product_title"%>
      <%= submit_tag "Create product and import reviews"%>
    <% end %>
  </div>

  <%=link_to "All products", products_path %>
</div>